export default {
	canvasSize: 600,
	navbarRadius: 200,
	selectedRadius: 120,
	optionRadius: 25,
	boundaryRandomness: 0.2,
	options: [{
		name: 'Bootstrap',
		icon: './assets/bootstrap.svg',
		color: '#563d7c',
		knowledge: 90
	}, {
		name: 'C',
		icon: './assets/c.svg',
		color: '#03599c',
		knowledge: 80
	}, {
		name: 'C++',
		icon: './assets/cplusplus.svg',
		color: '#004482',
		knowledge: 95
	}, {
		name: 'CSS',
		icon: './assets/css3.svg',
		color: '#0170ba',
		knowledge: 100
	}, {
		name: 'Firebase',
		icon: './assets/firebase.svg',
		color: '#f5820b',
		knowledge: 80
	}, {
		name: 'HTML',
		icon: './assets/html5.svg',
		color: '#e34c26',
		knowledge: 100
	}, {
		name: 'Javascript',
		icon: './assets/javascript.svg',
		color: '#f5de19',
		knowledge: 90
	}, {
		name: 'Jquery',
		icon: './assets/jquery.svg',
		color: '#1169ad',
		knowledge: 40
	}, {
		name: 'MongoDB',
		icon: './assets/mongodb.svg',
		color: '#449a45',
		knowledge: 70
	}, {
		name: 'NodeJS',
		icon: './assets/node-dot-js.svg',
		color: '#77b063',
		knowledge: 100
	}, {
		name: 'Python',
		icon: './assets/python.svg',
		color: '#417bc4',
		knowledge: 80
	}, {
		name: 'ReactJS',
		icon: './assets/react.svg',
		color: '#53c1de',
		knowledge: 100
	}]
};